-- TASK-19: snapshot of the GameSpot production schema on 2026-08-15.
--
-- This migration intentionally preserves the current production behaviour,
-- including grants and RPC exposure that will be hardened by later tasks.
-- It contains schema/configuration only: no production users or application data.

create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_cron with schema pg_catalog;

create type public.teams as enum ('Team Alpha', 'Team Beta');

create table public.parks (
    id uuid not null default gen_random_uuid(),
    created_at timestamptz not null default now(),
    name text not null,
    latitude double precision not null,
    longitude double precision not null,
    address text not null,
    is_active boolean not null default false,
    has_lighting boolean not null default false,
    constraint parks_pkey primary key (id),
    constraint parks_name_key unique (name)
);

create table public.sports (
    id uuid not null default gen_random_uuid(),
    created_at timestamptz not null default now(),
    name text not null,
    players_per_team smallint not null default 5,
    duration_minutes smallint not null default 60,
    minimum_players_for_rewards smallint not null default 6,
    constraint sports_pkey primary key (id),
    constraint sports_name_key unique (name)
);

create table public.profiles (
    id uuid not null default gen_random_uuid(),
    created_at timestamptz not null default now(),
    username text,
    avatar_url text,
    rating bigint not null default 0,
    games_played bigint not null default 0,
    mvp_count bigint not null default 0,
    perf_points bigint not null default 0,
    updated_at timestamptz not null default now(),
    is_onboarded boolean not null default false,
    favorite_sport_id uuid,
    is_profile_completed boolean not null default false,
    constraint profiles_pkey primary key (id),
    constraint profiles_username_key unique (username),
    constraint profiles_favorite_sport_id_fkey
        foreign key (favorite_sport_id) references public.sports (id)
);

create table public.parks_sports (
    id bigint generated by default as identity not null,
    created_at timestamptz not null default now(),
    park_id uuid default gen_random_uuid(),
    sport_id uuid default gen_random_uuid(),
    constraint parks_sports_pkey primary key (id),
    constraint parks_sports_park_id_fkey
        foreign key (park_id) references public.parks (id) on delete cascade,
    constraint parks_sports_sport_id_fkey
        foreign key (sport_id) references public.sports (id) on delete cascade
);

create table public.parks_hour (
    id bigint generated by default as identity not null,
    created_at timestamptz not null default now(),
    park_id uuid,
    day_of_week smallint,
    open_hour timetz not null,
    close_time timetz not null,
    is_closed boolean not null,
    constraint parks_hour_pkey primary key (id),
    constraint parks_hour_park_id_fkey
        foreign key (park_id) references public.parks (id) on delete cascade
);

create table public.parks_images (
    id bigint generated by default as identity not null,
    created_at timestamptz not null default now(),
    park_id uuid,
    image_url text not null,
    is_main boolean not null,
    constraint parks_images_pkey primary key (id),
    constraint parks_images_park_id_fkey
        foreign key (park_id) references public.parks (id) on delete cascade
);

create table public.parks_ratings (
    id bigint generated by default as identity not null,
    created_at timestamptz not null default now(),
    park_id uuid,
    quality_avg real not null default 0,
    quality_count bigint not null default 0,
    facilities_avg real not null default 0,
    facilities_count bigint not null default 0,
    activity_avg real not null default 0,
    activity_count bigint not null default 0,
    overall_avg real not null default 0,
    updated_at timestamptz not null default now(),
    constraint parks_ratings_pkey primary key (id),
    constraint parks_ratings_park_id_fkey
        foreign key (park_id) references public.parks (id) on delete cascade
);

create table public.games (
    id uuid not null default gen_random_uuid(),
    created_at timestamptz not null default now(),
    park_id uuid,
    creator_id uuid,
    sport_id uuid,
    starts_at timestamptz not null,
    duration_minutes smallint not null,
    max_players smallint not null,
    is_finished boolean not null default false,
    is_processed boolean not null default false,
    is_in_progress boolean not null default false,
    mvp_voting_open boolean not null default false,
    participation_rewards_given boolean not null default false,
    constraint games_pkey primary key (id),
    constraint games_creator_id_fkey
        foreign key (creator_id) references public.profiles (id),
    constraint games_park_id_fkey
        foreign key (park_id) references public.parks (id) on delete cascade,
    constraint games_sport_id_fkey
        foreign key (sport_id) references public.sports (id)
);

create table public.game_members (
    id uuid not null default gen_random_uuid(),
    user_id uuid not null,
    game_id uuid not null,
    rating_change smallint not null default 0,
    perf_points_earned smallint not null default 0,
    was_mvp boolean not null default false,
    joined_at timestamptz not null default now(),
    team public.teams not null,
    constraint game_members_pkey primary key (id),
    constraint unique_game_member unique (game_id, user_id),
    constraint unique_member_per_game unique (game_id, user_id),
    constraint game_members_game_id_fkey
        foreign key (game_id) references public.games (id),
    constraint game_members_user_id_fkey
        foreign key (user_id) references public.profiles (id) on delete cascade
);

create table public.game_mvp_votes (
    id bigint generated by default as identity not null,
    created_at timestamptz not null default now(),
    voter_id uuid,
    voted_id uuid,
    game_id uuid,
    constraint game_mvp_votes_pkey primary key (id),
    constraint game_mvp_votes_game_id_voter_id_key unique (game_id, voter_id),
    constraint game_mvp_votes_game_id_fkey
        foreign key (game_id) references public.games (id) on delete cascade,
    constraint game_mvp_votes_voted_id_fkey
        foreign key (voted_id) references public.profiles (id) on delete cascade,
    constraint game_mvp_votes_voter_id_fkey
        foreign key (voter_id) references public.profiles (id) on delete cascade
);

create table public.user_sport_stats (
    id uuid not null default gen_random_uuid(),
    created_at timestamptz not null default now(),
    user_id uuid not null,
    sport_id uuid not null,
    rating bigint not null default 0,
    games_played bigint not null default 0,
    mvp_count bigint not null default 0,
    perf_points bigint not null default 0,
    updated_at timestamptz not null default now(),
    constraint user_sport_stats_pkey primary key (id),
    constraint user_sport_stats_sport_id_fkey
        foreign key (sport_id) references public.sports (id),
    constraint user_sport_stats_user_id_fkey
        foreign key (user_id) references public.profiles (id) on delete cascade
);

create table public.park_reviews (
    id uuid not null,
    user_id uuid not null,
    park_id uuid not null,
    created_at timestamptz default now(),
    quality smallint not null,
    facilities smallint not null,
    activity smallint not null,
    constraint park_reviews_pkey primary key (id),
    constraint park_reviews_user_id_park_id_key unique (user_id, park_id),
    constraint park_reviews_park_id_fkey
        foreign key (park_id) references public.parks (id) on delete cascade,
    constraint park_reviews_user_id_fkey
        foreign key (user_id) references public.profiles (id) on delete cascade
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
begin
  insert into public.profiles (id) values (new.id);
  return new;
end;
$$;

create or replace function public.create_user_sport_stats()
returns trigger
language plpgsql
as $$
begin
  insert into public.user_sport_stats (
    user_id, sport_id, rating, games_played, mvp_count, perf_points
  )
  select new.id, s.id, 0, 0, 0, 0
  from public.sports s
  where not exists (
    select 1
    from public.user_sport_stats uss
    where uss.user_id = new.id and uss.sport_id = s.id
  );
  return new;
end;
$$;

create or replace function public.create_game(
  p_park_id uuid,
  p_sport_id uuid,
  p_starts_at timestamptz
)
returns uuid
language plpgsql
security definer
as $$
declare
  v_user_id uuid;
  v_players_per_team int;
  v_duration_minutes int;
  v_game_id uuid;
  v_sport_exists boolean;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'Unauthorized';
  end if;

  select exists (
    select 1
    from public.parks_sports
    where park_id = p_park_id and sport_id = p_sport_id
  ) into v_sport_exists;

  if not v_sport_exists then
    raise exception 'Sport not available in this park';
  end if;

  select players_per_team, duration_minutes
  into v_players_per_team, v_duration_minutes
  from public.sports
  where id = p_sport_id;

  if exists (
    select 1
    from public.games g
    where g.park_id = p_park_id
      and g.is_finished = false
      and p_starts_at < g.starts_at + make_interval(mins => g.duration_minutes)
      and p_starts_at + make_interval(mins => v_duration_minutes) > g.starts_at
  ) then
    raise exception 'Another game already exists during this time';
  end if;

  insert into public.games (
    park_id, creator_id, sport_id, starts_at, duration_minutes, max_players
  ) values (
    p_park_id, v_user_id, p_sport_id, p_starts_at,
    v_duration_minutes, v_players_per_team * 2
  ) returning id into v_game_id;

  update public.profiles
  set perf_points = perf_points + 15
  where id = v_user_id;

  update public.user_sport_stats
  set perf_points = perf_points + 10
  where user_id = v_user_id and sport_id = p_sport_id;

  insert into public.game_members (game_id, user_id, team, was_mvp)
  values (v_game_id, v_user_id, 'Team Alpha', false);

  return v_game_id;
end;
$$;

create or replace function public.join_game(p_game_id uuid, p_team public.teams)
returns void
language plpgsql
security definer
as $$
declare
  v_user_id uuid;
  v_max_players int;
  v_team_limit int;
  v_team_count int;
  v_already_joined boolean;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'Unauthorized';
  end if;

  select max_players into v_max_players
  from public.games
  where id = p_game_id and is_finished = false;

  if v_max_players is null then
    raise exception 'Game not found';
  end if;

  select exists (
    select 1 from public.game_members
    where game_id = p_game_id and user_id = v_user_id
  ) into v_already_joined;

  if v_already_joined then
    raise exception 'User already joined';
  end if;

  v_team_limit := v_max_players / 2;

  select count(*) into v_team_count
  from public.game_members
  where game_id = p_game_id and team = p_team;

  if v_team_count >= v_team_limit then
    raise exception 'Team is full';
  end if;

  insert into public.game_members (game_id, user_id, team)
  values (p_game_id, v_user_id, p_team);
end;
$$;

create or replace function public.leave_game(p_game_id uuid)
returns void
language plpgsql
security definer
as $$
declare
  v_user_id uuid;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'Unauthorized';
  end if;

  delete from public.game_members
  where game_id = p_game_id and user_id = v_user_id;
end;
$$;

create or replace function public.get_game_by_id(p_game_id uuid)
returns table (
  id uuid,
  park_id uuid,
  creator_id uuid,
  starts_at timestamptz,
  duration_minutes integer,
  max_players integer,
  is_finished boolean,
  is_processed boolean,
  sport jsonb,
  joined_players integer
)
language sql
security definer
as $$
  select
    g.id,
    g.park_id,
    g.creator_id,
    g.starts_at,
    g.duration_minutes,
    g.max_players,
    g.is_finished,
    g.is_processed,
    jsonb_build_object('id', s.id, 'name', s.name) as sport,
    count(gm.id)::int as joined_players
  from public.games g
  join public.sports s on s.id = g.sport_id
  left join public.game_members gm on gm.game_id = g.id
  where g.id = p_game_id
  group by g.id, s.id;
$$;

create or replace function public.get_games_by_park(p_park_id uuid)
returns table (
  id uuid,
  park_id uuid,
  creator_id uuid,
  starts_at timestamptz,
  duration_minutes smallint,
  max_players smallint,
  is_finished boolean,
  is_processed boolean,
  is_in_progress boolean,
  mvp_voting_open boolean,
  sport jsonb,
  joined_players integer
)
language sql
security definer
as $$
  select
    g.id,
    g.park_id,
    g.creator_id,
    g.starts_at,
    g.duration_minutes,
    g.max_players,
    g.is_finished,
    g.is_processed,
    g.is_in_progress,
    g.mvp_voting_open,
    jsonb_build_object('id', s.id, 'name', s.name) as sport,
    count(gm.id)::int as joined_players
  from public.games g
  join public.sports s on s.id = g.sport_id
  left join public.game_members gm on gm.game_id = g.id
  where g.park_id = p_park_id
    and g.starts_at >= date_trunc('day', now()) - interval '1 day'
  group by g.id, s.id
  order by g.starts_at;
$$;

create or replace function public.get_user_games()
returns table (
  id uuid,
  park_id uuid,
  creator_id uuid,
  starts_at timestamptz,
  duration_minutes smallint,
  max_players smallint,
  is_finished boolean,
  is_processed boolean,
  is_in_progress boolean,
  mvp_voting_open boolean,
  sport jsonb,
  joined_players integer
)
language sql
security definer
as $$
  select
    g.id,
    g.park_id,
    g.creator_id,
    g.starts_at,
    g.duration_minutes,
    g.max_players,
    g.is_finished,
    g.is_processed,
    g.is_in_progress,
    g.mvp_voting_open,
    jsonb_build_object('id', s.id, 'name', s.name) as sport,
    count(gm2.id)::int as joined_players
  from public.game_members gm
  join public.games g on g.id = gm.game_id
  join public.sports s on s.id = g.sport_id
  left join public.game_members gm2 on gm2.game_id = g.id
  where gm.user_id = auth.uid()
    and g.starts_at >= date_trunc('day', now()) - interval '1 day'
  group by g.id, s.id
  order by g.starts_at;
$$;

create or replace function public.get_recent_matches()
returns table (
  id uuid,
  starts_at timestamptz,
  sport jsonb,
  rating_change integer,
  perf_points_earned integer,
  was_mvp boolean
)
language sql
security definer
set search_path to 'public'
as $$
  select
    g.id,
    g.starts_at,
    jsonb_build_object('id', s.id, 'name', s.name) as sport,
    coalesce(gm.rating_change, 0)::int as rating_change,
    coalesce(gm.perf_points_earned, 0)::int as perf_points_earned,
    coalesce(gm.was_mvp, false) as was_mvp
  from game_members gm
  join games g on g.id = gm.game_id
  join sports s on s.id = g.sport_id
  where gm.user_id = auth.uid() and g.is_finished = true
  order by g.starts_at desc
  limit 3;
$$;

create or replace function public.has_user_rated(p_user_id uuid, p_park_id uuid)
returns boolean
language sql
security definer
as $$
  select exists (
    select 1
    from public.park_reviews
    where user_id = p_user_id and park_id = p_park_id
  );
$$;

create or replace function public.get_game_details(p_game_id uuid)
returns table (
  id uuid,
  starts_at timestamptz,
  duration_minutes integer,
  max_players integer,
  joined_players integer,
  is_finished boolean,
  is_in_progress boolean,
  is_processed boolean,
  mvp_voting_open boolean,
  has_voted boolean,
  mvp_player jsonb,
  sport jsonb,
  park jsonb,
  players jsonb,
  is_joined boolean
)
language sql
security definer
set search_path to 'public'
as $$
  select
    g.id,
    g.starts_at,
    g.duration_minutes,
    g.max_players,
    count(gm.id)::int as joined_players,
    g.is_finished,
    g.is_in_progress,
    g.is_processed,
    g.mvp_voting_open,
    exists (
      select 1
      from game_mvp_votes gmv
      where gmv.game_id = g.id and gmv.voter_id = auth.uid()
    ) as has_voted,
    (
      select jsonb_build_object(
        'id', pr_mvp.id,
        'username', pr_mvp.username,
        'avatarUrl', pr_mvp.avatar_url,
        'rating', pr_mvp.rating,
        'votesCount', count(gmv.id)
      )
      from game_mvp_votes gmv
      join profiles pr_mvp on pr_mvp.id = gmv.voted_id
      where gmv.game_id = g.id
      group by pr_mvp.id
      order by count(gmv.id) desc
      limit 1
    ) as mvp_player,
    jsonb_build_object('id', s.id, 'name', s.name) as sport,
    jsonb_build_object(
      'id', p.id,
      'name', p.name,
      'latitude', p.latitude,
      'longitude', p.longitude,
      'hasLighting', p.has_lighting,
      'overallAvg', coalesce(prt.overall_avg, 0)
    ) as park,
    coalesce(
      jsonb_agg(
        distinct jsonb_build_object(
          'id', pr.id,
          'username', pr.username,
          'avatarUrl', pr.avatar_url,
          'rating', pr.rating,
          'gamesPlayed', pr.games_played,
          'createdAt', pr.created_at,
          'team', gm.team,
          'mvpVotesCount', (
            select count(*)
            from game_mvp_votes gmv
            where gmv.game_id = g.id and gmv.voted_id = pr.id
          ),
          'isVotedByCurrentUser', exists (
            select 1
            from game_mvp_votes gmv
            where gmv.game_id = g.id
              and gmv.voter_id = auth.uid()
              and gmv.voted_id = pr.id
          ),
          'isTopRated', pr.id = (
            select p1.id
            from profiles p1
            join game_members gm1 on gm1.user_id = p1.id
            where gm1.game_id = g.id
            order by p1.rating desc
            limit 1
          ),
          'isMostActive', pr.id = (
            select p2.id
            from profiles p2
            join game_members gm2 on gm2.user_id = p2.id
            where gm2.game_id = g.id
            order by p2.games_played desc
            limit 1
          ),
          'isNewest', pr.id = (
            select p3.id
            from profiles p3
            join game_members gm3 on gm3.user_id = p3.id
            where gm3.game_id = g.id
            order by p3.created_at desc
            limit 1
          )
        )
      ) filter (where pr.id is not null),
      '[]'
    ) as players,
    exists (
      select 1
      from game_members gm2
      where gm2.game_id = g.id and gm2.user_id = auth.uid()
    ) as is_joined
  from games g
  join sports s on s.id = g.sport_id
  join parks p on p.id = g.park_id
  left join game_members gm on gm.game_id = g.id
  left join profiles pr on pr.id = gm.user_id
  left join parks_ratings prt on prt.park_id = p.id
  where g.id = p_game_id
  group by g.id, s.id, p.id, prt.id;
$$;

create or replace function public.rate_park(
  p_user_id uuid,
  p_park_id uuid,
  p_quality integer,
  p_facilities integer,
  p_activity integer
)
returns void
language plpgsql
security definer
as $$
declare
  existing_review record;
  r record;
begin
  if auth.uid() is null or auth.uid() != p_user_id then
    raise exception 'unauthorized';
  end if;

  if p_quality < 1 or p_quality > 5
    or p_facilities < 1 or p_facilities > 5
    or p_activity < 1 or p_activity > 5 then
    raise exception 'invalid rating values';
  end if;

  select * into existing_review
  from public.park_reviews
  where user_id = p_user_id and park_id = p_park_id;

  if found then
    update public.park_reviews
    set quality = p_quality,
        facilities = p_facilities,
        activity = p_activity
    where user_id = p_user_id and park_id = p_park_id;
  else
    insert into public.park_reviews (
      id, user_id, park_id, quality, facilities, activity
    ) values (
      gen_random_uuid(), p_user_id, p_park_id,
      p_quality, p_facilities, p_activity
    );
  end if;

  select
    avg(quality)::numeric(3,2) as quality_avg,
    avg(facilities)::numeric(3,2) as facilities_avg,
    avg(activity)::numeric(3,2) as activity_avg,
    count(*) as total
  into r
  from public.park_reviews
  where park_id = p_park_id;

  update public.parks_ratings
  set quality_avg = coalesce(r.quality_avg, 0),
      facilities_avg = coalesce(r.facilities_avg, 0),
      activity_avg = coalesce(r.activity_avg, 0),
      overall_avg = (
        coalesce(r.quality_avg, 0)
        + coalesce(r.facilities_avg, 0)
        + coalesce(r.activity_avg, 0)
      ) / 3.0,
      quality_count = r.total,
      facilities_count = r.total,
      activity_count = r.total,
      updated_at = now()
  where park_id = p_park_id;
end;
$$;

create or replace function public.vote_mvp(p_game_id uuid, p_voted_user_id uuid)
returns void
language plpgsql
security definer
as $$
declare
  v_user_id uuid;
  v_voting_open boolean;
  v_is_finished boolean;
  v_voter_exists boolean;
  v_target_exists boolean;
  v_already_voted boolean;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'Unauthorized';
  end if;
  if v_user_id = p_voted_user_id then
    raise exception 'You cannot vote for yourself';
  end if;

  select mvp_voting_open, is_finished
  into v_voting_open, v_is_finished
  from public.games
  where id = p_game_id;

  if not v_voting_open then
    raise exception 'MVP voting is closed';
  end if;
  if v_is_finished then
    raise exception 'Game already finished';
  end if;

  select exists (
    select 1 from public.game_members
    where game_id = p_game_id and user_id = v_user_id
  ) into v_voter_exists;
  if not v_voter_exists then
    raise exception 'You are not a participant';
  end if;

  select exists (
    select 1 from public.game_members
    where game_id = p_game_id and user_id = p_voted_user_id
  ) into v_target_exists;
  if not v_target_exists then
    raise exception 'Player is not in this game';
  end if;

  select exists (
    select 1 from public.game_mvp_votes
    where game_id = p_game_id and voter_id = v_user_id
  ) into v_already_voted;
  if v_already_voted then
    raise exception 'You already voted';
  end if;

  insert into public.game_mvp_votes (game_id, voter_id, voted_id)
  values (p_game_id, v_user_id, p_voted_user_id);

  update public.profiles
  set perf_points = perf_points + 2
  where id = v_user_id;
end;
$$;

create or replace function public.start_games()
returns void
language plpgsql
security definer
as $$
begin
  update public.games
  set is_in_progress = true
  where is_in_progress = false
    and is_finished = false
    and starts_at <= now();
end;
$$;

create or replace function public.finish_games()
returns void
language plpgsql
security definer
as $$
begin
  update public.games g
  set is_finished = true,
      is_in_progress = false,
      mvp_voting_open = true
  from public.sports s
  where s.id = g.sport_id
    and g.is_in_progress = true
    and g.is_finished = false
    and g.starts_at + make_interval(mins => s.duration_minutes) <= now();
end;
$$;

create or replace function public.open_mvp_voting()
returns void
language plpgsql
security definer
as $$
declare
  v_game record;
begin
  for v_game in
    select g.id, g.sport_id, g.max_players, s.minimum_players_for_rewards
    from public.games g
    join public.sports s on s.id = g.sport_id
    where g.is_in_progress = true
      and g.is_finished = false
      and g.mvp_voting_open = false
      and g.participation_rewards_given = false
      and g.starts_at + make_interval(secs => 20) <= now()
  loop
    if (
      select count(*) from public.game_members gm where gm.game_id = v_game.id
    ) >= v_game.minimum_players_for_rewards then
      update public.profiles
      set rating = rating + 10,
          games_played = games_played + 1,
          perf_points = perf_points + 35
      where id in (
        select user_id from public.game_members where game_id = v_game.id
      );

      update public.user_sport_stats uss
      set rating = uss.rating + 15,
          games_played = uss.games_played + 1,
          perf_points = uss.perf_points + 40
      where uss.sport_id = v_game.sport_id
        and uss.user_id in (
          select user_id from public.game_members where game_id = v_game.id
        );

      update public.game_members
      set rating_change = 15, perf_points_earned = 40
      where game_id = v_game.id;

      update public.games
      set mvp_voting_open = true,
          participation_rewards_given = true
      where id = v_game.id;
    end if;
  end loop;
end;
$$;

create or replace function public.process_finished_games()
returns void
language plpgsql
security definer
as $$
declare
  v_game record;
  v_mvp_user_id uuid;
  v_votes_count int;
begin
  for v_game in
    select g.id, g.sport_id
    from public.games g
    where g.is_finished = true
      and g.is_processed = false
      and g.mvp_voting_open = true
      and g.starts_at + make_interval(mins => 3) <= now()
  loop
    select gmv.voted_id into v_mvp_user_id
    from public.game_mvp_votes gmv
    where gmv.game_id = v_game.id
    group by gmv.voted_id
    order by count(*) desc, random()
    limit 1;

    if v_mvp_user_id is not null then
      select count(*) into v_votes_count
      from public.game_mvp_votes
      where game_id = v_game.id and voted_id = v_mvp_user_id;

      update public.profiles
      set rating = rating + 25 + (v_votes_count * 3),
          perf_points = perf_points + 70 + (v_votes_count * 8),
          mvp_count = mvp_count + 1
      where id = v_mvp_user_id;

      update public.user_sport_stats
      set rating = rating + 35 + (v_votes_count * 5),
          perf_points = perf_points + 80 + (v_votes_count * 10),
          mvp_count = mvp_count + 1
      where user_id = v_mvp_user_id and sport_id = v_game.sport_id;

      update public.game_members
      set was_mvp = true,
          rating_change = rating_change + 35 + (v_votes_count * 5),
          perf_points_earned = perf_points_earned + 80 + (v_votes_count * 10)
      where game_id = v_game.id and user_id = v_mvp_user_id;
    end if;

    update public.games
    set is_in_progress = false,
        mvp_voting_open = false,
        is_processed = true
    where id = v_game.id;
  end loop;
end;
$$;

-- Development-only debug RPCs are intentionally not recreated. Their production
-- definitions embed user UUIDs and are removed by a follow-up migration.

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create trigger on_profile_created
after insert on public.profiles
for each row execute function public.create_user_sport_stats();

alter table public.game_members enable row level security;
alter table public.game_mvp_votes enable row level security;
alter table public.games enable row level security;
alter table public.park_reviews enable row level security;
alter table public.parks enable row level security;
alter table public.parks_hour enable row level security;
alter table public.parks_images enable row level security;
alter table public.parks_ratings enable row level security;
alter table public.parks_sports enable row level security;
alter table public.profiles enable row level security;
alter table public.sports enable row level security;
alter table public.user_sport_stats enable row level security;

create policy "Authenticated users can join games"
on public.game_members
for insert
to authenticated
with check (true);

create policy "Game members are viewable by everyone"
on public.game_members
for select
to public
using (true);

create policy "Authenticated users can vote"
on public.game_mvp_votes
for insert
to authenticated
with check (true);

create policy "MVP votes are viewable by everyone"
on public.game_mvp_votes
for select
to public
using (true);

create policy "Authenticated users can create games"
on public.games
for insert
to authenticated
with check (true);

create policy "Games are viewable by everyone"
on public.games
for select
to public
using (true);

create policy "Authenticated users can create park reviews"
on public.park_reviews
for insert
to authenticated
with check (true);

create policy "Park reviews are viewable by everyone"
on public.park_reviews
for select
to public
using (true);

create policy "Park reviews are updateable by everyone"
on public.park_reviews
for update
to public
using (true);

create policy "Parks are viewable by everyone"
on public.parks
for select
to public
using (true);

create policy "Park hours are viewable by everyone"
on public.parks_hour
for select
to public
using (true);

create policy "Park images are viewable by everyone"
on public.parks_images
for select
to public
using (true);

create policy "Authenticated users can create park ratings"
on public.parks_ratings
for insert
to authenticated
with check (true);

create policy "Authenticated users can update park ratings"
on public.parks_ratings
for update
to authenticated
using (true)
with check (true);

create policy "Park ratings are viewable by everyone"
on public.parks_ratings
for select
to public
using (true);

create policy "Park sports are viewable by everyone"
on public.parks_sports
for select
to public
using (true);

create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = id);

create policy "Realtime profiles readable"
on public.profiles
for select
to authenticated
using (true);

create policy "Users can update own profile"
on public.profiles
for update
to public
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "Users can upload own profile"
on public.profiles
for update
to public
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "Sports are viewable by everyone"
on public.sports
for select
to public
using (true);

create policy "Users can view own sport stats"
on public.user_sport_stats
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Realtime stats readable"
on public.user_sport_stats
for select
to authenticated
using (true);

grant all privileges on table
  public.game_members,
  public.game_mvp_votes,
  public.games,
  public.parks,
  public.parks_hour,
  public.parks_images,
  public.parks_ratings,
  public.parks_sports,
  public.profiles,
  public.sports,
  public.user_sport_stats
to anon, authenticated, service_role;

grant references, trigger, truncate
on table public.park_reviews
to anon, authenticated, service_role;

grant usage on sequence
  public.game_mvp_votes_id_seq,
  public.parks_hour_id_seq,
  public.parks_images_id_seq,
  public.parks_ratings_id_seq,
  public.parks_sports_id_seq
to anon, authenticated, service_role;

-- Current production exposes every public RPC to all Data API roles. This is
-- captured for parity and is intentionally tightened by a later security task.
grant execute on all functions in schema public
to anon, authenticated, service_role;

insert into storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types, avif_autodetection
)
values ('avatars', 'avatars', true, null, null, false)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types,
    avif_autodetection = excluded.avif_autodetection;

create policy "Public read avatars"
on storage.objects
for select
to public
using (bucket_id = 'avatars');

create policy "Users insert own avatar"
on storage.objects
for insert
to public
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and (storage.foldername(name))[1] <> ''
);

create policy "Users update own avatar"
on storage.objects
for update
to public
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and (storage.foldername(name))[1] <> ''
);

do $$
declare
  relation_name text;
begin
  foreach relation_name in array array[
    'game_members',
    'game_mvp_votes',
    'games',
    'profiles',
    'sports',
    'user_sport_stats'
  ]
  loop
    if not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = relation_name
    ) then
      execute format(
        'alter publication supabase_realtime add table public.%I',
        relation_name
      );
    end if;
  end loop;
end;
$$;

select cron.schedule('finish-games', '* * * * *', 'select finish_games();');
select cron.schedule('open-mvp-voting', '* * * * *', 'select open_mvp_voting();');
select cron.schedule(
  'process-finished-games',
  '* * * * *',
  'select process_finished_games();'
);
select cron.schedule('start-games', '* * * * *', 'select start_games();');
